config/routes.rb
Rails.application.routes.draw do

  resources :contents
  devise_for :users
    root 'pages#home'
    
    get 'about' => 'pages#about'
    
    post '/buy/:slug', to: 'transaction#create', as: :buy
    get '/pickup/:guid', to: 'transaction#pickup', as: :pickup
    
    get 'dashboard' => 'pages#dashboard'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ActiveRecord::Base

extend FriendlyId
friendly_id :title, use: :slugged
    
belongs_to :user
    
    
has_many :sales    
    
    has_attached_file :cover
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
    message: "Only image formats are supported"
    
    # has_attached_file :allegato
   # validates_attachment_content_type :attachment, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ], 
    # message: "Format not supported"
    
validates :title, :description, :price, presence: true

validates :price, numericality: { greater_than: 0.49 }

validates :cover, attachment_presence: true
    
    
end

app/models/sale.rb
class Sale < ApplicationRecord
    
    before_create :generate_guid
    belongs_to :content
    
    include AASM
    
    aasm column: 'state' do
        state :sleeping, :initial => true
        state :running 
        state :completed
        state :errored
        
        
        event :running, after: :charge_card do
            transitions from: :sleeping, to: :running
        end  
        
        event :complete do 
            transitions from: :running, to: :completed
        end
        
        event :fail do 
            transitions from: :running, to: :errored
        end    
    end    
    
    def charge_card
        
        begin
           save! 
            charge = Stripe::Charge.create(
                amount: self.amount,
                currency: "usd",    
                card: self.stripe_token,
                description: "sale of a content"
                )
            self.update(stripe_id: charge.id)
            self.complete!
            
        rescue Stripe::StripeError => e
            self.update_attributes(error: e.message)
            self.fail!
        end    
    
    end    
    
    private
    
        def generate_guid
            self.guid = SecureRandom.uuid()
        end    
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :contents

    validates :name, presence: true    



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.  
    # encoding: utf-8


    
    protect_from_forgery with: :exception
    
before_action :configure_permitted_parameters, if: :devise_controller?
    
 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end    

end

app/controllers/concerns/transaction_controller.rb
class TransactionController < ApplicationController
    # encoding: utf-8


    
    def create
        content = Content.find_by!(slug: params[:slug])
        sale = content.sales.create(
            amount: (content.price * 100).floor,
            email_buyer: current_user.email,
            email_seller: content.user.email,
            stripe_token: params[:stripeToken])
        sale.running!
        
        if sale.completed?
            redirect_to pickup_url(guid: sale.guid)
        else
            redirect_to content_path(content), notice: @error
        end    
    end
    
    
    def pickup
        @sale = Sale.find_by!(guid: params[:guid])
        @content = @sale.content   
    end
    
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # encoding: utf-8


    
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]
  
  def index
    @contents =     @contents = Content.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
  end

  
  def show
  end

  
  def new
    @content = current_user.contents.build
  end

  
  def edit
  end

  
  def create
    @content = current_user.contents.build(content_params)


    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_content
      @content = Content.friendly.find(params[:id])
    end

    
    def content_params
      params.require(:content).permit(:title, :description, :price, :cover, :attachment)
    
end
    
    def check_user
      if current_user != @content.user 
          redirect_to root_url, alert: "You don't have the permission to perform such an action"
            end
        end
    end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
    # encoding: utf-8


    
    before_action :authenticate_user!, only: [:dashboard]
  
  def home
  end

  def about
  end

  def dashboard
  	@content = current_user.contents
  	@sales = Sale.where(email_seller: current_user.email)
  	@purchased = Sale.where(email_buyer: current_user.email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, html: { multipart: true } do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- <div class="field">
    <label class="grey-text">Upload a picture of the area you want to share</label>
    <p><%= f.file_field :attachment %></p> 
 </div> -->
  <br>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "materialize-textarea" %>
  </div>

  
  <div class="field">
    <%= f.label :price_per_hour_minimum_50_cent %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    
    <%= f.file_field :cover %>
  </div>
    <br>
  <div class="actions">
    <%= f.submit 'Upload content', class: "btn btn-form" %>
  </div>

<br>

<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Editing Content <em class="content-color"><%= @content.title %></em></h1>

<%= render 'form' %>

<%= link_to 'Show contents', @content %> |
<%= link_to 'Back to contents', contents_path %>

app/views/contents/index.html.erb
<div class="row">
  <% @contents.each do |content| %>
    <div class="col s12 m6 l4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag content.cover.url, class: "activator" %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= content.title %><i class="material-icons right">more_vert</i></span>
          <div>
            <span>Venduto da <%= content.user.name %></span>
            <span class="right"><%= number_to_currency(content.price) %></span>
          </div>
          <br>
          <div class="center"><%= link_to 'Scopri di più', content, class: "btn" %></div>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= content.title %><i class="material-icons right">close</i></span>
          <p><%= content.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<div class="center">
  <%= will_paginate @contents %>
</div>

app/views/contents/new.html.erb
<h1 class="center">Add Content</h1>

<%= render 'form' %>

<%= link_to 'Back to contents', contents_path %>

app/views/contents/show.html.erb
<div class="row">

    <div class="col l6">
    
        <%= image_tag @content.cover.url, class: "responsive-img show-img" %>
        
    </div>
    
    <div class="col l6">
    
        
          
        <h1 class="show-title"><%= @content.title %></h1>

        <h4 class="show-price"> <%= number_to_currency(@content.price) %></h4>
    
        <p> Sold by  <%= @content.user.name %></p> 
        
        <p>
     
          <%= @content.description %>
        </p>

        
<% if current_user %>

    <%= form_tag buy_path(slug: @content.slug) do %>
      <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-amount="<%= (@content.price * 100).floor %>"
        data-name="SharingPal"
        data-description="<%= @content.title %>"  
        data-email="<%= current_user.email %>"   
        data-locale="auto">
      </script>
    <% end %>
        
       <!-- <div class="wrapper">
 
<div class="wrapper">
 
    <div id="map">
        <span class="helper">Click the button below to show your location on the map</span>
        <img id="preloader" src="images/257.gif">
    </div>
 
    <a class="button" href="" title="">Find My Location</a>
 
    <div id="results">
        <span class="longitude"></span><br>
        <span class="lattitude"></span><br>
        <span class="location"></span>
    </div>
     
</div><!--End Wrapper-->
            
<% else %>
    <p><%= link_to "Log in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %> to buy </p>

<% end %>
        
    
    </div>
    
</div>



<% if @content.user == current_user %>
    <%= link_to 'Edit', edit_content_path(@content) %> 
<% end %>

<%= link_to 'Back to contents', contents_path %>

app/views/layouts/_footer.html.erb
<br>
<footer class="page-footer blue-grey darken-2 center">
     
          <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col s4">
                © 2017 SharingPal
            </div>
                <div class="col s4">
                    <a href="#" target="_blank"><i class="fa-social fa fa-facebook fa-2x white-text"></i></a>
                    <a href="#" target="_blank"><i class="fa-social fa fa-twitter fa-2x white-text"></i></a>
                    <a href="https://www.instagram.com/sharingpal/" target="_blank"><i class="fa-social fa fa-instagram fa-2x white-text"></i></a>
                </div>
                    <div class="col s4">
                    <%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
                    </div>
            </div>    
          </div>
        </footer>
            

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
	<nav class="blue-grey darken-2">
	    <div class="container nav-wrapper">
	    	<%= link_to 'SharingPal'.html_safe, root_path, class: "brand-logo" %>
	      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
	      <ul class="right hide-on-med-and-down">
	      	<li><%= link_to 'Share a service', new_content_path %></li>
	        <li><%= link_to 'Find the service you need', contents_path %></li>
	        
            <% if user_signed_in? %>

	        <ul id="dropdown1" class="dropdown-content">
				<li><%= link_to "Dashboard", dashboard_path %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
			</ul>
	        	<li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
	        <% else %>
	        	<li><%= link_to "Log In", new_user_session_path %></li>
	        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
	        <% end %>
	        
	      </ul>
            
        </div>
	</nav>
</header>
	      <ul class="side-nav" id="mobile-demo">
	      	<li><%= link_to 'Share a service', new_content_path %></li>
	        <% if user_signed_in? %>
                <ul id="dropdown1" class="dropdown-content">
				<li><%= link_to "Dashboard", dashboard_path %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
			</ul>
	        	<li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
              
	        <% else %>
	        	<li><%= link_to "Log In", new_user_session_path %></li>
	        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
	        <% end %>
	      </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    
    <title>SharingPal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet" type="text/css">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
</head>
<body>     

<%= render "layouts/header" %>    

        <div class="container">
          <% flash.each do |type, message| %>
          <script>
            Materialize.toast('<%= message %>', 4000)
          </script>
          <% end %>
        </div>
    
<%= render 'pages/slider' if action_name == 'home' %>  
    
<main class="container">  
    
<%= yield %>

</main>      

<%= render "layouts/footer" %>
    
    
</body>

  
	<script>
	 $(".button-collapse").sideNav();
	</script>

  <script>
  $(document).ready(function(){
  $('ul.tabs').tabs();
  });
  </script>
    
    <script>
    
         $(document).ready(function(){
         $('.parallax').parallax();
         });
        
        
    </script>

  <script>
  $(document).ready(function(){
  $(".dropdown-button").dropdown();
  });
  </script>  

</html>

app/views/layouts/getstarted.html.erb
<h1>Already registered?</h1>


<%= link_to "Login", registrations_path, class: "btn red btn-large" %>


<h1>Not yet registered? </h1>

<%= link_to "Sign Up", registrations_path, class: "btn red btn-large" %>

app/views/pages/about.html.erb
<html>
   
<h1>About us</h1>

<p>We are a team of developers who provide sharing economy services</p>

    
</html>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>
    
  <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a href="#previoustransactions">Sales</a></li>
        <li class="tab col s3"><a href="#purchase">Currently on sale</a></li>
      </ul>
    </div>
        <div id="previoustransactions" class="col s12">
            <h4>Sales</h4>
            <table>
            
                <thead>
                    
                    <tr>
                    
                        <th>Name</th>
                        <th>Price</th>
                        <th>Date</th>
                        <th>Buyer</th>
                    </tr>
                    </thead>
                <tbody>
                
                    <% @sales.each do |sale| %>
                    <tr>
                    
                        <th><%= sale.content.title %></th>
                        <th><%= number_to_currency(sale.amount/100) %></th>
                        <th><%= time_ago_in_words(sale.created_at) %> ago </th>
                        <th><%= sale.email_buyer %></th>
                    </tr>
                    <% end %>
                </tbody>
                
                
            </table>
      
        <h4>Purchases</h4>
            
                        <table>
            
                <thead>
                    
                    <tr>
                    
                        <th>Name</th>
                        <th>Price</th>
                        <th>Creation date</th>
                        <th>Seller</th>
                    </tr>
                    </thead>
                <tbody>
                
                    <% @purchased.each do |purchased| %>
                    <tr>
                    
                        <th><%= link_to purchased.content.title, pickup_path(purchased.guid) %></th>
                        <th><%= number_to_currency(purchased.amount / 100) %></th>
                        <th><%= time_ago_in_words(purchased.created_at) %> ago </th>
                        <th>purc</th>
                    </tr>
                    <% end %>
                </tbody>
                
                
            </table>
        
        </div>
        <div id="purchase" class="col s12">
            <table>
            
                <thead>
                    
                    <tr>
                    
                        <th>Name</th>
                        <th>Price</th>
                        <th>Creation date</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                <tbody>
                
                    <% @content.each do |content| %>
                    <tr>
                    
                        <th><%= link_to content.title, content_path(content) %></th>
                        <th><%= number_to_currency(content.price) %></th>
                        <th><%= time_ago_in_words(content.created_at) %> ago </th>
                        <th><%= link_to "Edit", edit_content_path(content) %> |
                            <%= link_to "Delete", content, method: :delete, data: {confirm: 'Are you sure you want to delete this content?'} %>
                            </th>
                    </tr>
                    <% end %>
                </tbody>
                
                
            </table>
      
      
      </div>
  </div>

app/views/pages/home.html.erb
<div class="center">

  <div class="row">
    <h2 class="home-subtitle">What can you do with SharingPal?</h2>
    <div class="col s12 m4">
      <i class="material-icons medium blue-grey-text text-darken-3">library_books</i>
      <h5>What you can find on SharingPal</h5>
      <p>There are no limits to the types of short-term sharing services you can provide or ask: from making your house become a coworking space, to share your oven or your burner, to rent out your bed or your sofa to people who want to take a quick nap, to rent out your toilet; it is everything up to your fantasy.  </p>
    </div>
    <div class="col s12 m4">
      <i class="material-icons medium blue-grey-text text-darken-3">motorcycle</i>
      <h5>Become a host</h5>
      <p>Both to earn extra income from their spare space and to know new people: hosts use SharingPal for a variety of reasons. Be one of them. </p>
    </div>
    <div class="col s12 m4">
      <i class="material-icons medium blue-grey-text text-darken-3">library_add</i>
      <h5>Find a host</h5>
      <p>Either you are a freelancer tired of the high fees of coworking spaces, or you are in need of an oven or a burner to prepare your meal, or you just want to take a quick nap before restarting your activities, SharingPal is precisely what you need: Cheap, safe and easy to use. </p>
    </div>
  </div>
</div>

app/views/transaction/pickup.html.erb
<h1>Thanks for your purchase</h1>
<p><%= link_to "Click here" %> to print your receipt</p>